method: grid
metric:
  goal: minimize
  name: test_loss
parameters:
  norm:
    values:
    #- none
    - layer_norm
    #- feature_norm
    - set_norm
  task:
    values:
    - hematocrit_categorical
    - hematocrit_small
    #- pointcloud
    #- mnistvar
    #- normalvar
  model:
    values:
    - deepsets
  size:
    values:
    - 25
  seed:
    values:
    - 0
    - 1
    - 2
program: experiments/deep_sets_analysis.py
project: results

