method: grid
metric:
  goal: minimize
  name: test_loss
parameters:
  norm:
    values:
    #- none
    - layer_norm
    - set_norm
    #- feature_norm
  task:
    values:
    - hematocrit_categorical
    - hematocrit_small
    #- pointcloud
    #- mnistvar
    #- normalvar
  model:
   values:
   - settransformer
   - settransformer2
  seed:
    values:
    - 0
    - 1
    - 2
  size:
    values:
     - 16
program: experiments/set_transformer_analysis.py
project: results

